[package]
name = "mica-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "9.1.2"
structopt = "0.3.26"

mica-language = { path = "../mica-language" }
